version: "2.24.0"
services:

  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytest
    ports:
      - "8000:80"
    env_file:
      - .test.env
    command: sh -c "pytest -v"




