version: "2.24.0"
services:
  db:
    image: postgres:15.1-alpine
    container_name: db_ylab_api_prod
    env_file:
      - .prod.env
    command: -p ${DB_PORT_PROD}
    ports:
      - ${DB_PORT_PROD}:${DB_PORT_PROD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready",  "-d",  "${DB_NAME_PROD}",  "-U" , "${POSTGRES_USER}", '-p', '${DB_PORT_PROD}' ]
      interval: 10s
      timeout: 30s
      retries: 5

  db_test:
    image: postgres:15.1-alpine
    container_name: db_ylab_api_test
    env_file:
      - .test.env
    ports:
      - ${DB_PORT_TEST}:${DB_PORT_TEST}
    command: -p ${DB_PORT_TEST}
    expose:
      - ${DB_PORT_TEST}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready",  "-d",  "${DB_NAME_TEST}",  "-U" , "${POSTGRES_USER}", '-p', '${DB_PORT_TEST}' ]
      interval: 10s
      timeout: 30s
      retries: 5

  app:
    build:
      context: .
    env_file:
      - .prod.env
    container_name: ylab_api_prod
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - 9000:8000
    depends_on:
      db:
        condition: service_healthy

  app_test:
    build:
      context: .
    env_file:
      - .test.env
    container_name: ylab_api_test
    command: [ "/fastapi_app/docker/app_test.sh" ]
    ports:
      - 9876:8765
    depends_on:
      db_test:
        condition: service_healthy



