version: "2.24.0"
services:
  db:
    image: postgres:15.1-alpine
    container_name: db_ylab_api_prod
    env_file:
      - .prod.env
    ports:
      - ${DB_PORT_PROD}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready",  "-d",  "${DB_NAME_PROD}",  "-U" , "${POSTGRES_USER_PROD}" ]
      interval: 10s
      timeout: 30s
      retries: 5

  db_test:
    image: postgres:15.1-alpine
    container_name: db_ylab_api_test
    env_file:
      - .test.env
    ports:
      - ${DB_PORT_TEST}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready",  "-d",  "${DB_NAME_TEST}",  "-U" , "${POSTGRES_USER_TEST}"]
      interval: 10s
      timeout: 30s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis_prod
    ports:
      - ${REDIS_PORT_PROD}:6379
    env_file:
      - .prod.env
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  redis_test:
    image: redis:latest
    container_name: redis_test
    ports:
      - ${REDIS_PORT_TEST}:6379
    env_file:
      - .test.env
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
    env_file:
      - .prod.env
    container_name: ylab_api_prod
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  app_test:
    build:
      context: .
    env_file:
      - .test.env
    container_name: ylab_api_test
    command: [ "/fastapi_app/docker/app_test.sh" ]
    ports:
      - 8003:8765
    depends_on:
      db_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy


