version: "2.24.0"
services:
  db:
    image: postgres:15.1-alpine
    container_name: db_ylab_api
    env_file:
      - src/.env
    ports:
      - 5432:5432

  app_test:
    build:
      context: .
    env_file:
      - src/.test.env
    container_name: ylab_api_test
    command: ["/fastapi_app/docker/app_test.sh"]
    ports:
      - 9876:8765
    depends_on:
      - db

  app:
    build:
      context: .
    env_file:
      - src/.env
    container_name: ylab_api_prod
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - 9000:8000
    depends_on:
      - db

